module.exports = {
    parser: '@typescript-eslint/parser',
    extends: [
        'eslint-config-airbnb-base',
        'plugin:@typescript-eslint/recommended',
        'eslint-config-prettier',
        'plugin:prettier/recommended',
        'plugin:import/typescript',
    ],
    rules: {
        'import/prefer-default-export': 'off',
        'import/no-extraneous-dependencies': 'off',
        'import/extensions': 'off',
        'import/no-anonymous-default-export': 'off',
        'max-classes-per-file': 'off',
        'one-var': 'off',
        '@typescript-eslint/no-unused-vars': ['warn'],
        'no-return-assign': 'off',
        'no-underscore-dangle': 'off',
        'no-unused-expressions': ['error', { allowShortCircuit: true }],
        '@typescript-eslint/ban-ts-comment': 'off',
        'func-names': 'off',
        '@typescript-eslint/prefer-optional-chain': 'error',
        'logical-assignment-operators': ['error', 'always'],
        'no-plusplus': 'off',
        'no-prototype-builtins': 'off',
    },
};
